### ISSUE TITLE
Green grass does not start the camera/Rollback error after deleting things and 

### ISSUE THREAD

**Issue by FarouqMotamed** [aws-samples/aws-iot-greengrass-deploy-nvidia-deepstream-on-edge#3]
Hi,

Following your webinar, I need to run a usb camera connected to a jetson tx2 using greengrass.
 I have already run the camera using deepstream on jetson TX2 without greengrass. I changed the deepstream configuration file to tun the camera as below.

[source0]
enable=1
#Type - 1=CameraV4L2 2=URI 3=MultiURI 4=RTSP
type=1
camera-width=640
camera-height=480
camera-fps-n=30
camera-fps-d=1
camera-v4l2-dev-node=0

[sink0]
enable=1
#Type - 1=FakeSink 2=EglSink 3=File 4=RTSPStreaming 5=Overlay
type=2
sync=0
display-id=0

I completed the installation steps and ran the greengrass successfully. But the camera does not start and nothing shows up. How do I fix this problem? I have attached the deepstream config file. 

After this problem, I deleted all the things on AWS and tried to install greengrass all over again. But this time I got the rollback error. I tried this process several times, but each time I got the rollback error. I have attached the screen shot for the error. Please provide instructions on how to fix these problems. 
Regards,
Farough

![Screenshot+from+2021-01-25+20-50-58](https://user-images.githubusercontent.com/45321904/105895001-2dbc0600-5fd2-11eb-9026-d424e73d95b8.png)
[source1_usb_dec_infer_resnet_int8.txt](https://github.com/aws-samples/aws-iot-greengrass-deploy-nvidia-deepstream-on-edge/files/5875604/source1_usb_dec_infer_resnet_int8.txt)

**Comment by yuxiny2586** [comment]
Regarding the rollback: Once GG is deployed, you will need to manually reset the current deployment before you can delete/change the existing CloudFormation stack.
Regarding USB camera issue, could you go into your greengrass Lambda log on your TX2 and post them here for us to debug?
Thanks!

**Comment by FarouqMotamed** [comment]
I  followed your webinar and completed the webinar to the end and deployed
the Greengrass on TX2.
Since the camera did not work, I deleted the greengrass folder on Tx2, and
deleted the things on the aws, then opened the cloudformation in aws and
deleted the stack too. This is the current situation.

I don't know how to manually reset the current deployment. Please advise
....
I can send you the greengrass lambda log on TX2 once I deploy the
greengrass again.


Regards,
Farough

**Comment by FarouqMotamed** [comment]
Still I don't know how to fix the rollback error. Attached is a snap shot.
There is no option to manually resume the deployment.

**Comment by yuxiny2586** [comment]
Could you take a screenshot of the cloudformation page on your AWS console? Especially on the event page where this formation template is failing. Thanks!

**Comment by FarouqMotamed** [comment]
Attached please find pictures from the floudformation page and events
pages.
Please let me know how to fix the problems.
Thanks!

**Comment by yuxiny2586** [comment]
For some reason, the attachment did not show up. Please navigate to AWS console -> IoT -> Greengrass -> groups. Click into the group that you want to delete, and on the upper right corner, click on the drop down menu, and reset deployment (force rest). And delete the cloudformation stack before trying again. Let me know if this works.

**Comment by FarouqMotamed** [comment]
The is no greengrass group in my aws console and there is no reset
deployment option.
I already deleted the group and the deployment.

I attached the pictures again.

Regards,
Farough

**Comment by AndreV84** [comment]
Hi guys, how is it going? I am just wondering which exactly webinar is being reffered to. Are you reffering to the webinar "Build with Deepstream, deploy and manage with AWS IoT services" or some different webinar? Thanks

@yuxiny2586 could you also address the issue https://github.com/aws-samples/aws-iot-greengrass-deploy-nvidia-deepstream-on-edge/issues/4 , please?

**Comment by FarouqMotamed** [comment]
Yes, it's the webinar you are referring to.

this is the link:

https://info.nvidia.com/deepstream-aws-iot-webinar-reg-page.html?ondemandrgt=yes

thanks

**Comment by yuxiny2586** [comment]
This issue was resolved by going into AWS IoT thing page and manually deleting things and thing policies.
